# Generated by Django 3.1.2 on 2020-11-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_auto_20201106_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='gamer',
            new_name='organizer',
        ),
    ]
