# Generated by Django 3.1.2 on 2020-11-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_auto_20201106_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='description',
        ),
    ]
